services:
  flutter:
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        FLUTTER_IMAGE: ${FLUTTER_IMAGE:-ghcr.io/cirruslabs/flutter:stable@sha256:7f429b29a9568705def6308f94458633e7c21d8dcf14fe6e1762f9ced3ba83b8}
    working_dir: /workspace
    volumes:
      - ./:/workspace
      - flutter_pub_cache:/root/.pub-cache
    stdin_open: true
    tty: true

volumes:
  flutter_pub_cache:
